LDLIBS = -std=c++17
CC = g++

day1:
	${CC} aoc1.cc -o aoc1 ${LDLIBS}
day2:
	${CC} aoc2.cc -o aoc2 ${LDLIBS}
day3:
	${CC} aoc3.cc -o aoc3 ${LDLIBS}
day4:
	${CC} aoc4.cc -o aoc4 ${LDLIBS}
day5:
	${CC} aoc5.cc -o aoc5 ${LDLIBS}
day6:
	${CC} aoc6.cc -o aoc6 ${LDLIBS}
day7:
	${CC} aoc7.cc -o aoc7 ${LDLIBS}
day8:
	${CC} aoc8.cc -o aoc8 ${LDLIBS}
day9:
	${CC} aoc9.cc -o aoc9 ${LDLIBS}
day10:
	${CC} aoc10.cc -o aoc10 ${LDLIBS}
day11:
	${CC} aoc11.cc -o aoc11 ${LDLIBS}
day12:
	${CC} aoc12.cc -o aoc12 ${LDLIBS}
day13:
	${CC} aoc13.cc -o aoc13 ${LDLIBS}