LDLIBS = -std=c++17
CC = g++

day1:
	${CC} aoc1.cc -o aoc1 ${LDLIBS}
day2:
	${CC} aoc2.cc -o aoc2 ${LDLIBS}
day3:
	${CC} aoc3.cc -o aoc3 ${LDLIBS}
day4:
	${CC} aoc4.cc -o aoc4 ${LDLIBS}
day5:
	${CC} aoc5.cc -o aoc5 ${LDLIBS}